name: delimatrix_dart
description: Delimatrix transforms strings to objects and back with a touch of magic
version: 0.4.0
homepage: https://github.com/flarebyte/delimatrix_dart
repository: https://github.com/flarebyte/delimatrix_dart
topics:
  - json
  - serialization
  - encoding
environment:
  sdk: ^3.1.4
dev_dependencies:
  lints: ^4.0.0
  test: ^1.21.0
